<a href="https://colab.research.google.com/github/Aleksandra2002/obliczenia_naukowe/blob/main/lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

%time - policzy ile czasu robi polecenie (magic)
%timeit - liczy 

In [3]:
import numpy as np
#funkcja licząca pole między wykresem a osią OX
#wyr - funkcja
#przedział (a,b)
#N - liczba kroków/podziałów
#N-1 - liczba odcinków
np.linspace(0,1,10) #podział na N punktów

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [18]:
def calka(funkcja,a,b,N):
  podzial=np.linspace(a,b,N)
  podstawa = (b-a)/(N-1)
  wartosc=0
  for i in range (N-1):
    wartosc += podstawa*abs(funkcja(podzial[i]))
  return wartosc
calka(lambda x:x**2,0,1,100)
  

0.3282998333503384


#NUMPY - tworzy tablice/listy



ndim - ile ma wymiarów
size - ile ma elementów ta tablica
dtype - jakie mamy typy
nbytes - ile zajmuje pamięci tablica

In [22]:
tab =np.array([[1,2],[3,4],[4,1]])
tab.dtype

dtype('int64')

In [27]:
tablica = np.array([[1,3,5],[1,6,8],[3,4,5],[3,4,9]])
print (tablica.size, tablica.ndim,tablica.nbytes)

12 2 96


In [29]:
#zamiana typu z int na float
tablica1=np.array(tablica,dtype=float)
tablica1

array([[1., 3., 5.],
       [1., 6., 8.],
       [3., 4., 5.],
       [3., 4., 9.]])

In [36]:
tab3=np.array([-1,0,1])
np.sqrt(tab3)
tab4=tab3.astype(complex) #zamiana int z tab3 na zespolone w tab4
tab4
np.sqrt(tab4).imag #bierzemy czesci całkowite

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


array([1., 0., 0.])

In [37]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.meshgrid([1,2,3],['a','b','c'])

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), array([['a', 'a', 'a'],
        ['b', 'b', 'b'],
        ['c', 'c', 'c']], dtype='<U1')]

In [48]:
np.ones((2,2))
np.zeros((7,7))
from scipy.linalg import block_diag
Mat1=block_diag(np.ones((2,2)),np.zeros((2,2)),3,(4*np.ones((2,2))-2*np.diag((1,1))))

In [54]:
Mat1

array([[1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0., 2., 4.],
       [0., 0., 0., 0., 0., 4., 2.]])

In [49]:
Mat1[:,::-1] #odwraca

array([[0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0.],
       [4., 2., 0., 0., 0., 0., 0.],
       [2., 4., 0., 0., 0., 0., 0.]])

In [63]:
#zad5
Mat1
Mat1[0:4,0:4]
Mat1[4::,4::]
Mat2=block_diag(Mat1[0:4,0:4],Mat1[4::,4::])
Mat2

array([[1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0., 2., 4.],
       [0., 0., 0., 0., 0., 4., 2.]])

In [65]:
Mat3=Mat2[1::2,1::2]
Mat3

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 2.]])