<a href="https://colab.research.google.com/github/Aleksandra2002/obliczenia_naukowe/blob/main/lab_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy.linalg import block_diag

In [ ]:
Mat1=block_diag(np.ones((2,2)),np.zeros((2,2)),3,(4*np.ones((2,2))-2*np.diag((1,1))))

In [ ]:
Mat1.reshape((1,49)) #zmiana kształtu tablicy

array([[1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        3., 0., 0., 0., 0., 0., 0., 0., 2., 4., 0., 0., 0., 0., 0., 4.,
        2.]])

In [ ]:
tab=np.array([[2,3],[4,5],[6,7]])
tab

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
tab.reshape(-1) #wszystkie wartości tablicy w liście

array([2, 3, 4, 5, 6, 7])

In [ ]:
tab2=np.arange(1,17) #lista od 1 do 16
tab2.reshape((4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
tab3=np.array([[1,2]])
tab4=np.array([[2],[1]])
tab8=tab3+tab4

In [ ]:
tab5=np.ones((2,2))

In [ ]:
tab6=np.arange(1,9)
tab7=tab6.reshape((2,4))
tab7
#tab6+tab7 nie da się

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
#zadanie do domu 5x6x3 
#numpy mnoży każdy element

In [ ]:
tab9=3*np.eye(2)*np.ones((2,2)) #mnoży każdy element ze sobą, nie jak w algebrze
tab9

array([[3., 0.],
       [0., 3.]])

In [ ]:
A=np.sin(tab7) #sin każdego wyrazu tablicy
A

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825]])

In [ ]:
tab8**tab9 #potęgowanie tablicy do potęgi tablicy

array([[27.,  1.],
       [ 1., 27.]])

In [ ]:
A.T #transponowanie A

array([[ 0.84147098, -0.95892427],
       [ 0.90929743, -0.2794155 ],
       [ 0.14112001,  0.6569866 ],
       [-0.7568025 ,  0.98935825]])

In [ ]:
B=np.arange(1,17)
B
B.T #transpozycja na wektorach nie działa bo B.T=B

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

## AGREGACJA

In [ ]:
tab

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
np.mean(tab,axis=0) #srednia wzdłuż kolumn
np.mean(tab,axis=1) #srednia wzdluz wierszy

array([2.5, 4.5, 6.5])

In [ ]:
tablica=np.random.random(100)
tablica
np.sum(tablica)

46.19077695078282

In [ ]:
np.cumsum(tab7) 

array([ 1,  3,  6, 10, 15, 21, 28, 36])

In [ ]:
np.cumsum(tab7,axis=1)

array([[ 1,  3,  6, 10],
       [ 5, 11, 18, 26]])

In [ ]:
tab7>5

array([[False, False, False, False],
       [False,  True,  True,  True]])

In [ ]:
tab7[tab7>5] #tworzy liste tych wartosci ktore spelniaja warunek

array([6, 7, 8])

In [ ]:
tab7*(tab7>5) #1 gdy true, 0 gdy False

array([[0, 0, 0, 0],
       [0, 6, 7, 8]])

In [ ]:
#nie da się ifa po tablicach

In [ ]:
#można tylko all lub any
if np.all(tab7>5):
  print('tak')
else:
  print('nie')

nie


In [ ]:
L=np.arange(1,17).reshape((4,4))
L
x=np.array([1,2,3,4])
y=np.array([0,4,1,6])

In [ ]:
x<y #wiersz

array([False,  True, False,  True])

In [ ]:
L[x<y] #slad na tabeli L, wzielo tylko 2 i 4 wiersz z L, bierze w pionie
#bo 2 i 4 true w x<y

array([[ 5,  6,  7,  8],
       [13, 14, 15, 16]])

In [ ]:
#praca domowa
#maska, zliczyć jedynki czyli suma

## ALGEBRA LINIOWA

In [ ]:
C=np.array([[1,2,4],[4,6,8],[8,10,12]])
C

array([[ 1,  2,  4],
       [ 4,  6,  8],
       [ 8, 10, 12]])

In [ ]:
np.linalg.inv(C) #macierz odwrotna

array([[ 1.  , -2.  ,  1.  ],
       [-2.  ,  2.5 , -1.  ],
       [ 1.  , -0.75,  0.25]])

In [ ]:
#zmiana bazy C=BAB**-1
A1=np.array([[2,3],[0,2]])
B1=np.array([[2,5],[3,8]])
C=np.dot(B1,np.dot(A1,np.linalg.inv(B1)))
C


array([[-16.,  12.],
       [-27.,  20.]])

In [ ]:
np.linalg.eig(A1)[0]

array([2., 2.])

In [ ]:
np.linalg.eig(A1)[1] #odczytujemy wektor [1,0] i [-1,1]

array([[ 1.00000000e+00, -1.00000000e+00],
       [ 0.00000000e+00,  1.48029737e-16]])

In [ ]:
np.linalg.eig(A1)[1][:,0]
np.linalg.eig(C)[0]

array([2.+1.97405238e-07j, 2.-1.97405238e-07j])