<a href="https://colab.research.google.com/github/Aleksandra2002/obliczenia_naukowe/blob/main/lab_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Algebra liniowa w Pythonie
* ```np.linalg.inv ``` - odwrotność macierzy
* ```np.linalg.det``` - wyznacznik
* ```np.linalg.eig``` - wartości i wektory własne
* ```np.dot``` - iloczyn macierzowy
* ```np.inner``` - iloczyn skalarny
* ```np.cross``` - iloczyn wektorowy

* ```np.linalg.norm``` - norma macierzy lub wektora

In [14]:
import numpy as np
A=np.random.random((5,5))
B =np.linalg.eig(A)
%timeit np.linalg.eig(A) #ile czasu się wykonuje to polecenie
type(B)

The slowest run took 5.70 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 32.5 µs per loop


tuple

In [17]:
np.max(B[0])

(2.868021933923659+0j)

In [27]:
mat1= np.array([[2,0],[1,1]])
wyz= np.linalg.det(mat1)
mat2 = np.dot(mat1,np.dot(np.diag([1,2]),np.linalg.inv(mat1)))

In [28]:
np.linalg.eig(mat2)

(array([2., 1.]), array([[0.        , 0.89442719],
        [1.        , 0.4472136 ]]))

In [29]:
mat1 @ mat1 #mnożenie macierzy

array([[4, 0],
       [3, 1]])

In [31]:
np.dot(mat1,mat1)

array([[4, 0],
       [3, 1]])

In [34]:
#SVD - rozklad macierzy
SVD = np.linalg.svd(A) #macierz(ortogonalna), przekątna (diagonalna), macierz(ortogonalna)

In [36]:
SVD[0]@ np.diag(SVD[1]) @SVD[2] - A

array([[ 2.77555756e-16,  5.55111512e-16,  6.66133815e-16,
         1.24900090e-16,  7.77156117e-16],
       [ 6.66133815e-16,  6.66133815e-16,  5.55111512e-16,
         2.22044605e-16,  4.44089210e-16],
       [ 4.44089210e-16,  3.33066907e-16,  3.33066907e-16,
        -5.55111512e-17,  4.44089210e-16],
       [ 4.44089210e-16,  4.99600361e-16,  1.11022302e-16,
         4.44089210e-16,  3.33066907e-16],
       [ 1.11022302e-16,  2.63677968e-16,  2.77555756e-16,
         1.66533454e-16,  1.92554306e-16]])

In [39]:
(SVD[0] @ SVD[0].T).round(0)

array([[ 1.,  0.,  0., -0.,  0.],
       [ 0.,  1.,  0., -0.,  0.],
       [ 0.,  0.,  1., -0., -0.],
       [-0., -0., -0.,  1.,  0.],
       [ 0.,  0., -0.,  0.,  1.]])

In [41]:
m2 = np.array([[1,2,3],[1,2,1],[0,1,0]])
np.linalg.eig(m2)

(array([ 3.45667834+0.j        , -0.22833917+0.72556968j,
        -0.22833917-0.72556968j]),
 array([[ 0.74635087+0.j        , -0.85289345+0.j        ,
         -0.85289345-0.j        ],
        [ 0.63933662+0.j        ,  0.21479077+0.23188188j,
          0.21479077-0.23188188j],
        [ 0.18495693+0.j        ,  0.20602029-0.36086579j,
          0.20602029+0.36086579j]]))

In [43]:
 np.linalg.svd(m2)

(array([[-0.8384388 , -0.50673863, -0.20058996],
        [-0.52438113,  0.6498237 ,  0.55023049],
        [-0.14847494,  0.56652018, -0.81056158]]),
 array([4.39972444, 1.22684012, 0.37052417]),
 array([[-0.3097512 , -0.65324882, -0.69088362],
        [ 0.11662894,  0.69502969, -0.70945854],
        [ 0.94363758, -0.30033266, -0.13909856]]))

In [63]:
m3 = m2[0:2]
m4 =np.linalg.svd(m3)
m4


(array([[-0.85065081, -0.52573111],
        [-0.52573111,  0.85065081]]),
 array([4.3525018, 1.0274863]),
 array([[-3.16227766e-01, -6.32455532e-01, -7.07106781e-01],
        [ 3.16227766e-01,  6.32455532e-01, -7.07106781e-01],
        [-8.94427191e-01,  4.47213595e-01, -2.22044605e-16]]))

In [64]:
sigma = np.concatenate([np.diag(m4[1]),np.zeros((2,1))],axis=1)

In [66]:
m4[0] @ sigma @ m4[2]

array([[1., 2., 3.],
       [1., 2., 1.]])

In [71]:
np.linalg.matrix_power(m2,20) #podnoszenie macierzy do potęgi 20tej

array([[16968908951, 41687151125, 26786952325],
       [14535850675, 35709909551, 22946150525],
       [ 4205149925, 10330700750,  6638208201]])

In [82]:
rozsvd =np.linalg.eig(m2)
JA = np.diag(rozsvd[0])
P=rozsvd[1]
(P @ JA**20 @ np.linalg.inv(P)).round(0)

array([[1.69689090e+10-0.j, 4.16871511e+10+0.j, 2.67869523e+10+0.j],
       [1.45358507e+10-0.j, 3.57099096e+10+0.j, 2.29461505e+10-0.j],
       [4.20514992e+09-0.j, 1.03307008e+10+0.j, 6.63820820e+09+0.j]])

In [86]:
#ROZWIĄZYWANIE układów równań
np.linalg.cond(m2) #mówi jak nasza macierz jest czuła na błąd wyniku - WSKAŹNIK UWARUNKOWANIA
#np.linalg.solve() #rozwiązuje równania

11.87432495287239

In [106]:
A= np.array([[1,0,2],[3,2,1],[1,1,1]])
b1= np.array([20.001,-9.999,100.00001])
b2=np.array([20,-10,100])
np.linalg.cond(A)

10.617346008950063

In [105]:
np.linalg.solve(A,b1)

array([-133.33234667,  156.66568333,   76.66667333])

In [107]:
np.linalg.solve(A,b2)

array([-133.33333333,  156.66666667,   76.66666667])