<a href="https://colab.research.google.com/github/Aleksandra2002/obliczenia_naukowe/blob/main/zadDomowe5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Zadanie

1. Wygeneruj losową tablicę L(100x10) liczb całkowitych z przedziału [0,10] generatorem=12345 (```np.random.seed(12345)``` przed użyciem ```np.random.random_integers```. Sprawdź:
* ile jest w niej liczb większych od 3
* jaka jest średnia w każdej kolumnie
* określ w których wierszach co najmniej połowa liczb jest $\geq 5$
* wypisz kolejno (wierszami) wszysktie elementy tablicy z przedziału [2,5]. 
* stwórz nową talibcę, zerując w L wszysktie elementy spoza przedziału [2,5].
* znajdź wiersze, które nie zawierają żadnego zera

In [2]:
import numpy as np
np.random.seed(12345)
Mat1 = np.random.random_integers(0,10,size=(100,10))
Mat1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  This is separate from the ipykernel package so we can avoid doing imports until


array([[ 2,  5,  1,  4,  9,  5,  2,  1,  6,  1],
       [ 9,  7,  6,  0,  2,  9, 10,  1,  2,  6],
       [ 7,  7,  7,  8,  7,  1,  7,  4,  0,  3],
       [ 5,  7,  3,  1,  5,  2,  5,  3,  8,  5],
       [ 2,  5,  3,  0,  6,  8,  0,  5, 10,  6],
       [ 8,  9,  2,  2,  2,  9, 10,  7,  5,  7],
       [ 1,  0, 10,  9, 10,  3,  0,  3,  0,  6],
       [ 2,  1,  5,  8,  6,  5,  1,  0,  5,  8],
       [ 2,  9,  4,  7,  9,  5,  2,  4,  8,  2],
       [ 5,  6,  5,  9,  6,  1,  9,  5,  0,  8],
       [ 8,  2, 10,  0,  2,  0,  6,  5,  3,  2],
       [ 7,  4,  7,  2,  3,  6,  0,  5,  4,  1],
       [ 9,  5,  1,  2,  3,  8,  0,  9,  3,  5],
       [ 3,  8,  9,  3, 10,  8,  9,  7,  4,  9],
       [ 8,  9,  0,  1,  6,  6,  2,  0,  5,  7],
       [ 8,  2,  5,  6,  1,  9,  0, 10,  8, 10],
       [10,  7,  6,  9,  5,  5,  0,  0, 10,  2],
       [10,  3,  1,  9, 10,  3,  5,  2,  1,  0],
       [ 7,  3,  1,  9, 10,  2,  8,  0,  6,  9],
       [ 0,  0,  8,  3,  7,  9,  5,  2,  8,  5],
       [ 0,  4,  6, 

In [6]:
#a Ile jest liczb większych niż 3?
Mat2=1*(Mat1>3) 
np.sum(Mat2)

615

In [7]:
#b Jaka jest średnia w każdej kolumnie?
np.mean(Mat1,axis=0)

array([5.28, 4.7 , 4.43, 4.64, 5.51, 4.82, 4.66, 5.22, 4.62, 4.85])

In [8]:
#c określ w których wierszach co najmniej połowa liczb jest ≥5
listadobra =[]
listazla = []
Mat3=1*(Mat1 >=5)
for i in range (0,100):
  if np.sum(Mat3[i])>=5:
    listadobra.append(i+1)
  else:
    listazla.append(i+1)
print('Numery wierszy w których co najmniej połowa liczb jest nie mniejsza od 5:', listadobra)
print('Numery wierszy w których co najmniej połowa liczb jest mniejsza od 5:', listazla)

Numery wierszy w których co najmniej połowa liczb jest nie mniejsza od 5: [2, 3, 4, 5, 6, 8, 9, 10, 13, 14, 15, 16, 17, 19, 20, 23, 24, 25, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 43, 44, 46, 49, 52, 53, 56, 57, 58, 59, 60, 62, 63, 65, 66, 67, 71, 72, 75, 76, 77, 79, 80, 81, 82, 83, 84, 85, 86, 88, 89, 91, 92, 94, 95, 97, 98, 100]
Numery wierszy w których co najmniej połowa liczb jest mniejsza od 5: [1, 7, 11, 12, 18, 21, 22, 26, 27, 42, 45, 47, 48, 50, 51, 54, 55, 61, 64, 68, 69, 70, 73, 74, 78, 87, 90, 93, 96, 99]


In [9]:
#e stwórz nową talibcę, zerując w L wszysktie elementy spoza przedziału [2,5].
condlist=[Mat1<2,Mat1>5]
choicelist=[0*Mat1,0*Mat1]
L=np.select(condlist, choicelist,Mat1)
L

array([[2, 5, 0, 4, 0, 5, 2, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 4, 0, 3],
       [5, 0, 3, 0, 5, 2, 5, 3, 0, 5],
       [2, 5, 3, 0, 0, 0, 0, 5, 0, 0],
       [0, 0, 2, 2, 2, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 3, 0, 3, 0, 0],
       [2, 0, 5, 0, 0, 5, 0, 0, 5, 0],
       [2, 0, 4, 0, 0, 5, 2, 4, 0, 2],
       [5, 0, 5, 0, 0, 0, 0, 5, 0, 0],
       [0, 2, 0, 0, 2, 0, 0, 5, 3, 2],
       [0, 4, 0, 2, 3, 0, 0, 5, 4, 0],
       [0, 5, 0, 2, 3, 0, 0, 0, 3, 5],
       [3, 0, 0, 3, 0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0, 2, 0, 5, 0],
       [0, 2, 5, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 5, 0, 0, 0, 2],
       [0, 3, 0, 0, 0, 3, 5, 2, 0, 0],
       [0, 3, 0, 0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 5, 2, 0, 5],
       [0, 4, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 5, 0, 5, 2, 2],
       [0, 0, 4, 5, 0, 5, 2, 0, 2, 0],
       [3, 0, 0, 0, 0, 0, 0, 0, 2, 0],
       [2, 0, 0, 0, 0, 0, 0, 4, 3, 3],
       [2, 0, 0, 3, 5, 0,

In [5]:
#f znajdź wiersze, które nie zawierają żadnego zera
Mat1[np.nonzero(Mat1)]


array([ 2,  5,  1,  4,  9,  5,  2,  1,  6,  1,  9,  7,  6,  2,  9, 10,  1,
        2,  6,  7,  7,  7,  8,  7,  1,  7,  4,  3,  5,  7,  3,  1,  5,  2,
        5,  3,  8,  5,  2,  5,  3,  6,  8,  5, 10,  6,  8,  9,  2,  2,  2,
        9, 10,  7,  5,  7,  1, 10,  9, 10,  3,  3,  6,  2,  1,  5,  8,  6,
        5,  1,  5,  8,  2,  9,  4,  7,  9,  5,  2,  4,  8,  2,  5,  6,  5,
        9,  6,  1,  9,  5,  8,  8,  2, 10,  2,  6,  5,  3,  2,  7,  4,  7,
        2,  3,  6,  5,  4,  1,  9,  5,  1,  2,  3,  8,  9,  3,  5,  3,  8,
        9,  3, 10,  8,  9,  7,  4,  9,  8,  9,  1,  6,  6,  2,  5,  7,  8,
        2,  5,  6,  1,  9, 10,  8, 10, 10,  7,  6,  9,  5,  5, 10,  2, 10,
        3,  1,  9, 10,  3,  5,  2,  1,  7,  3,  1,  9, 10,  2,  8,  6,  9,
        8,  3,  7,  9,  5,  2,  8,  5,  4,  6,  8,  6,  1,  1,  1,  8,  1,
        2, 10,  5,  1,  5,  2,  2,  8,  1,  4,  5,  8,  5,  2,  7,  2,  9,
        3,  1,  8,  8,  9,  6,  2,  7,  2,  7,  1,  9,  7, 10,  6,  4,  3,
        3,  2, 10,  1,  3